application: csa-match
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: main.py

libraries:
- name: jinja2
  version: "2.6"